### ISSUE TITLE
Comments and question on 0.6.0 launch

### ISSUE THREAD

**Issue by ddkothar** [melonproject/ipfs-frontend#176] opened 2018-01-23 18:27 UTC
Please ignore comments or question which are stupid.

1) will the option to put password be mandatory before every order execution? and what about forget a password.
2) Option to hide assets, which fund manager not interested (Like Hiding option)
3) Will there be an option for the chart in the future version?
4) Fund after shut down, following error.. Also after shutting down will melon be returned to previous address? will shut down fund ranking be still displayed?
5) Multiple Fund with same name. (How to eliminate confusion). e.g. check sample test
6) If I opened a Fund, can I also invest in others Fund?
7) Fund trading history (some time record same transaction multiple times)
8) Along with Twitter, is there plan link other social media platform.
9) Mobile (Smartphone, Ipads etc) support?
10) Will there be any section, which will show my investment in different Funds? if I want to invest in more than 1 fund.
11) For placing an order, (either market or Limit), If you put decimal order, e.g. for 0.5 worth of MLN. Total box, is generating random numbers.
try, typing 0.5. it think it's not recognizing keyboard decimal

**Comment by schmidsi** [comment] 2018-01-24 08:20
> Please ignore comments or question which are stupid.

There are no stupid questions. If some seem stupid to us, we may assumed some not so obvious things to be obvious.

> 
> 1) will the option to put password be mandatory before every order execution? and what about forget a password.

If you forget your password, you won't be able to unlock your private key again. So write down the seed words in the beginning. The frontend is fully decentralized, no helpdesk can reset your password.

> 2) Option to hide assets, which fund manager not interested (Like Hiding option)

There will be the option to pick your assets in the setup fund phase.

> 3) Will there be an option for the chart in the future version?

We are working on charts. Which one are you most interested in? History of share-price?

> 4) Fund after shut down, following error.. Also after shutting down will melon be returned to previous address? will shut down fund ranking be still displayed?

When shutting down a fund, all assets of the fund will be distributed in slices to the investors. Say you have 3 investors each holding 1/3 of shares and the fund holds one MLN and one ETH. By shutting down, each investor will receive 1/3 MLN and 1/3 ETH.

> 5) Multiple Fund with same name. (How to eliminate confusion). e.g. check sample test

It's not possible to setup a fund with an existing name. Names are unique.

> 6) If I opened a Fund, can I also invest in others Fund?

Yes.

> 7) Fund trading history (some time record same transaction multiple times)

There should be a history.

> 8) Along with Twitter, is there plan link other social media platform.

You can use the same link

> 9) Mobile (Smartphone, Ipads etc) support?

Yes. Should work.

> 10) Will there be any section, which will show my investment in different Funds? if I want to invest in more than 1 fund.

Good idea. There is an account page. We can add it there.

> 11) For placing an order, (either market or Limit), If you put decimal order, e.g. for 0.5 worth of MLN. Total box, is generating random numbers. try, typing 0.5. it think it's not recognizing keyboard decimal

You cannot place an order with quantities higher than your holdings. It is not super obvious that this is blocked, but was that what you tried?

**Comment by ddkothar** [comment] 2018-01-24 17:37
 This is encouraging, thank you for Answering.

1) okay, Seed phase is important. and the other part of the question is, before executing any order (Confirm transaction) need to put password every time (Can fund manager modify it, as in putting a password only when logging in to fund)
![image](https://user-images.githubusercontent.com/20861407/35344119-502b293a-00fa-11e8-8e04-e471f2242503.png)

3) Two types of chart, I think will be more helpful
    a) Fund Performance from the day of origin (Having markers which show when FUND has done some activity, e.g. Which Asset was bought or sold as per timestamp etc.
    b) Individual token (asset) price feed chart. Also if a marker is added when Fund manager bought or sold that particular asset.

4) Say, I don't have any investor and I am running fund by my own fund. I put 1 MLN in fund to start. In 0.6.0 Version when I am "Shut Down the Fund" K-MLN is not returning back to my K-ETH address. 

5) Check the Following screenshot (Fund with the same name)
![image](https://user-images.githubusercontent.com/20861407/35347239-843b2f74-0102-11e8-87cc-44628aeea005.png)


7) Following screen is what I mean by same transaction showing multiple times
![image](https://user-images.githubusercontent.com/20861407/35346817-48f3c26a-0101-11e8-9fd6-e3a7a3ce361d.png)

9) Will try using my Ipad (This will be awesome)

10) Yea, seeing how my investment is doing on single page will be helpful and I can manage better

11) Try writing 0.5 in Total using your Keyboard. It's not taking a decimal. And yes it makes obvious sense, that it will not take number higher than what Fund has
![image](https://user-images.githubusercontent.com/20861407/35347418-120c710a-0103-11e8-9a99-09a3eeba38dd.png)

**Comment by jennazenk** [comment] 2018-01-24 17:39
>Say, I don't have any investor and I am running fund by my own fund. I put 1 MLN in fund to start. In 0.6.0 Version when I am "Shut Down the Fund" K-MLN is not returning back to my K-ETH address.

It is not supposed to be returned back automatically. As per smart contract best practice, one should always "withdraw" from a contract; in that case, you would need to call a function to redeemOwnedAssets

**Comment by ddkothar** [comment] 2018-01-24 18:00
Yes, Redeem Feature works. 
Message Warning to make sure if manager has already withdrawn his Fund (So accidentally he/she does not shut down fund).

**Comment by jennazenk** [comment] 2018-01-24 18:12
After fund is shut down, any investor (included the fund manager) can still redeem their assets. It’s just a different function than the redeem used on the frontend right now

**Comment by schmidsi** [comment] 2018-01-25 09:23
> 1. okay, Seed phase is important. and the other part of the question is, before executing any order (Confirm transaction) need to put password every time (Can fund manager modify it, as in putting a password only when logging in to fund)

It's a security question: If we save the password of the manager somewhere in the browser, it would be possible for a malicious browser plugin to steal it. That said, our really secure live version will be inside Parity, possibly with hardware wallet support. But for now: Just use a password manager.

> 2. Two types of chart, I think will be more helpful

Cool. We'll look into this. Good idea with the indicators of trade/activity.

> 3. 

See @jennazenk's anser

> 4. (Double Names)

Oops. We need to investigate this.

> 5. Multiple trades

Oops. Seems like another bug. Thanks for reporting!

> 6. Ipad

Let us know if it works as expected

> 7. Fund History

Is in the making

> 8. Input Field / Decimals

Yep, I think I need to work again on this field.

**Comment by schmidsi** [comment] 2018-01-30 17:48
I cannot reproduce 5. The rest should be fixed in the next version (deployed tomorrow) or is in separate issues. Please check back tomorrow.

**Closed by schmidsi** 2018-01-30 17:48 UTC
