### ISSUE TITLE
interact with the Melon protocol

### ISSUE THREAD

**Issue by phantomracer** [melonproject/ipfs-frontend#72] opened 2017-11-25 18:05 UTC
Hi guys, 
Following your instructions, I switched to Kovan Test Network, but yet I can not interact with the protocol, despite all the refreshes I've done. 
What shall I do?

**Comment by schmidsi** [comment] 2017-11-29 08:34
I think this is a duplicate of #73.

**Closed by schmidsi** 2017-11-29 08:34 UTC
Labels: duplicate
