### ISSUE TITLE
Failed to get wallet balance

### ISSUE THREAD

**Issue by ShreyasChari** [melonproject/ipfs-frontend#260] opened 2018-03-21 18:18 UTC
I transferred 1 ETH and yet cannot see it in my wallet..The transaction has been verified but unable to proceed from the Faucet

**Comment by ferranbt** [comment] 2018-03-21 19:23
Thank you for the report. Indeed, it was an error on our side. Please try again the faucet and sorry for the inconvenience.

**Comment by schmidsi** [comment] 2018-03-22 16:11
Duplicate of #261

**Closed by schmidsi** 2018-03-22 16:11 UTC
