### ISSUE TITLE
Unable to adjust or add new positions in fund for weeks

### ISSUE THREAD

**Issue by mpquan** [melonproject/ipfs-frontend#79] opened 2017-12-10 18:21 UTC
Have attempted to buy and sell additional pairs in an established Melon fund (Oct 2017). Transaction starts and dialog appears, but MetaMask is never displayed for "submit". This state can last hours and still not resolve or provide error message. [MetaMask v. 3.13.2 and lastest Chrome]
Fixes attempted:
1) Refresh page and try again - Not fixed!
2) Lock and reopen MetaMask - Not fixed!
3) Combination of #1 & #2 - Not fixed!
4) Attempt to invest more to get more melon incase soem limit is being hit. - Unable to invest more; same issue.
5) Tried accessing through Mac OS instead of Windows 10 - Not fixed!
6) Tried- non Chrome browser (Brave) on Windows & Mac - Not fixed! Exhibited same spinning delay with MetaMask confirmation pop-ups.
7) Final try today - Same results. Attempted to "Irreversibly shut down fund" and start over.
  - Process proceed as expected. MetaMask popped up for confirmation and transaction looked like it worked. But on refresh it just reverted to the same state it has been in for weeks. Same positions, etc.

I just want to start over clean at this point and get out of this loop. Any suggestions or fixes underway?
Thanks!

**Comment by jennazenk** [comment] 2017-12-11 08:15
hello @mpquan, could you send me screenshots of the whole page so that I can try to find the issue you're encountering? 
In the meantime, if you want to start over it's easy, you just click on Metamask and create a new account; go to the faucet to get your account funded and then to melon.fund to set up a new fund.
Let me know how that goes :)

**Comment by mpquan** [comment] 2017-12-13 17:36
Hello @jennazenk 
Sorry for the delay. I have not been able to get back into my fund on my Windows w/Chrome laptop since I submitted the report. I used my Mac today with a new a MetaMask setup on the Brave browser. I was able to get into the Quan Fund again on this setup. 
However, the same issues occurred.  I am providing three screenshots to illustrate. The last one with "Executing your order" was spinning for 15 mins before I stopped it. MetaMask never popped up for submit confirmation. This spinning without a conclusion or error messaging happens on any pair I try to trade. 


![qfund1](https://user-images.githubusercontent.com/34422554/33953179-21740918-e002-11e7-8b4c-c428d36b1c56.jpg)
![qfund2](https://user-images.githubusercontent.com/34422554/33953186-24c12088-e002-11e7-99d2-a15514b68594.jpg)
![qfund3](https://user-images.githubusercontent.com/34422554/33953190-2905ce8c-e002-11e7-9d9e-fb1a00537283.jpg)

**Comment by jennazenk** [comment] 2017-12-13 18:41
hello @mpquan indeed thats very weird. It seems like you have a sufficient balance of GNT regarding to the amount you are trying to sell. I have tried to reproduce unfortunately I can't reproduce it, I am able to buy/sell GNT-T. I am trying to think of what could cause this on your end; need to investigate a bit more.. 
In the meantime, you can create a new metamask account, get your account funded on the Melon Faucet, and create a new fund. I will keep you posted here of my findings regarding that issue. 

Thanks again for reporting and taking the time to post screenshots!

**Comment by mpquan** [comment] 2017-12-15 14:35
Thanks @jennazenk I am glad it was helpful.

**Comment by jennazenk** [comment] 2018-01-29 16:37
Hey @mpquan there has been a new release (0.6) ; will close this, pls do not hesitate to re-open issue if you encounter the same problem :)

**Closed by jennazenk** 2018-01-29 16:37 UTC

**Comment by mpquan** [comment] 2018-01-29 22:45
0.6 closed the issue. Thx
