### ISSUE TITLE
Error notification to user

### ISSUE THREAD

**Issue by jennazenk** [melonproject/ipfs-frontend#60] opened 2017-10-26 23:20 UTC
- For investment process, when not enough MLN to reward workers
- When trade not executed / order not placed

We already have pretty explicit error messages from Melon.js in the console, but we need to decide how we transmit the message to user. -> to be discussed

**Comment by schmidsi** [comment] 2017-12-21 11:42
Duplicate of #92

**Closed by schmidsi** 2017-12-21 11:42 UTC
